[package]
name = "bevy_generative"
version = "0.1.0"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_egui = "0.21.0"
image = "0.24.6"
noise = { git = "https://github.com/Razaekel/noise-rs.git" }
